version: 2

references:
    spec: &spec
        machine: true

jobs:
    build_image:
        <<: *spec
        steps:
            - checkout
            - run: echo Code checked out
            - run:
                name: Build the build environment Docker image
                command: echo docker build -t $IMAGE_NAME tools/docker
            - run:
                name: Create build directory
                command: echo mkdir build
    configure:
        <<: *spec
        steps:
          - run:
              name: Run CMake
              command: echo docker run -v $PWD:/phylanx -w /phylanx/build -e "CIRCLECI=true" ${IMAGE_NAME} cmake -DPHYLANX_WITH_GIT_COMMIT=${CIRCLE_SHA1} -DPHYLANX_WITH_TOOLS=On -DHPX_DIR=/usr/local/lib/cmake/HPX -Dpybind11_DIR=/pybind11/share/cmake/pybind11/ -Dblaze_DIR=/blaze/share/blaze/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DPHYLANX_WITH_HIGHFIVE=On -DHighFive_DIR=/highfive/share/HighFive/CMake ..
    flake:
        <<: *spec
        steps:
          - run:
              name: Check the formatting of Phylanx's Python files
              command: echo docker run -v $PWD:/phylanx -w /phylanx ${IMAGE_NAME} flake8 --config=tools/flake8/config.ini .
    inspect:
        <<: *spec
        steps:
          - run:
              name: Build the Inspect tool
              command: echo docker run -v $PWD:/phylanx -w /phylanx/build ${IMAGE_NAME} make -j2 -k tools.inspect
          - run:
              name: Create artifact directory
              command: echo mkdir artifacts
          - run:
              name: Check the formatting of Phylanx's C++ files
              command: echo docker run -v $PWD:/phylanx -w /phylanx ${IMAGE_NAME} ./build/bin/inspect --all --output=./build/phylanx_inspect_report.html /phylanx
          - run:
              command: echo cp build/phylanx_inspect_report.html artifacts
          - store_artifacts:
              path: artifacts
    core:
        <<: *spec
        steps:
          - run:
              name: Build all targets
              command: echo docker run -v $PWD:/phylanx -w /phylanx/build ${IMAGE_NAME} make -j2
    tests:
        <<: *spec
        steps:
          - run:
              name: Run all tests
              command: echo docker run -v $PWD:/phylanx -w /phylanx/build ${IMAGE_NAME} make -j2 tests
    deploy:
        <<: *spec
        steps:
          - run:
              name: Push the Phylanx build environment Docker image
              command: |
                    echo 'if [ "$CIRCLE_BRANCH" == "master" ]; then'
                    echo '    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}'
                    echo '    docker push ${IMAGE_NAME}'
                    echo 'fi'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build_image
            - configure:
                requires:
                    - build_image
            - flake:
                requires:
                    - build_image
            - inspect:
                requires:
                    - configure
            - core:
                requires:
                    - inspect
            - tests:
                requires:
                    - core
            - deploy:
                requires:
                    - flake
                    - inspect
                    - tests
