version: 2

references:
    container: &container
        machine: true

jobs:
    checkout_code:
        <<: *container
        steps:
            - checkout
            - run: echo Code checked out

    display_message:
        <<: *container
        steps:
            - run:
                name: Greeting
                command: echo Hello, world.
    print_time:
        <<: *container
        steps:
          - run:
              name: Print the Current Time
              command: date

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - checkout_code
            - display_message:
                requires:
                    - checkout_code
            - print_time:
                requires:
                    - display_message
