version: 2

references:
    - &spec
        docker:
            - image: circleci/python:3-jessie
        #machine: true

jobs:
    main:
        <<: *spec
        working_directory: ~/ci-test
        steps:
            - checkout
            - run: echo Code checked out
            - run:
                name: Create build directory
                command: echo mkdir build
            - store_test_results:
                path: ~/ci-test/junit

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - main
