version: 2

references:
    spec: &spec
        machine: true

jobs:
    checkout_code:
        <<: *spec
        steps:
            - checkout
            - run: echo Code checked out

    build_image:
        <<: *spec
        steps:
            - run:
                name: Greeting
                command: echo Hello, world.
    configure:
        <<: *spec
        steps:
          - run:
              name: Print the Current Time
              command: date

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - checkout_code
            - build_image:
                requires:
                    - checkout_code
            - configure:
                requires:
                    - build_image
